version: '3.4'

services:
  api:
    build:
      context: .
      target: production
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
      DB_HOST: mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:27017
